
    
<%if(myOrganism.equals("Mm")){%>
	<%@ include file="regionResultsHelpMm.jsp" %>
<%}else if(myOrganism.equals("Rn")){%>
	<%@ include file="regionResultsHelpRn.jsp" %>
<%}%>
    


<div id="HelpUCSCImageContent" class="inpageHelpContent" title="<center>Help-UCSC Image</center>"><div class="help-content">
<H3>UCSC Genome Browser Image</H3>
The image displayed below is generated by the UCSC Genome Browser with a mix of data aggregated from PhenoGen, UCSC Genome Browser, and Ensembl.<BR /><BR />
Here is a quick primer if you are unfamiliar with the UCSC Genome Browser ?????.
<BR /><BR />
You may add tracks using the controls below.  All of the tracks are color coded based on their source and track or on the data itself.  Please see detailed descriptions of each track below or the legend for further details on the color coding and data contained in each track.
<BR />

</div></div>


<div id="HelpUCSCImageControlContent" class="inpageHelpContent" title="<center>Help-Image Controls</center>"><div class="help-content">
<H3>UCSC Image Controls</H3>


</div></div>


<script type="text/javascript">
//Setup Help links
	$('.inpageHelpContent').hide();
	
	$('.inpageHelpContent').dialog({ 
  		autoOpen: false,
		dialogClass: "helpDialog",
		width: 400,
		maxHeight: 500,
		zIndex: 9999
	});
</script>