<%--
 *  Author: Cheryl Hornbaker
 *  Created: Apr, 2005
 *  Description:  This file formats the files generated by the Promoter module.
 *
 *  Todo: 
 *  Modification Log:
 *      
--%>

<%@ include file="/web/geneLists/include/geneListHeader.jsp"  %> 

<jsp:useBean id="myPromoter" class="edu.ucdenver.ccp.PhenoGen.data.Promoter"> </jsp:useBean>
<% 	
	optionsList.add("geneListDetails");
	optionsList.add("chooseNewGeneList");

	userName = "";
	int itemID = Integer.parseInt((String) request.getParameter("itemID"));

	GeneListAnalysis thisGeneListAnalysis = myGeneListAnalysis.getGeneListAnalysis(itemID, dbConn);

	String searchRegionLevelText = thisGeneListAnalysis.getThisParameter("Search Region Level");
	String conservationLevelText = thisGeneListAnalysis.getThisParameter("Conservation Level");
	String thresholdLevelText = thisGeneListAnalysis.getThisParameter("Threshold Level");
	
	log.debug("in promoterResults. itemID = " + itemID);

	Promoter thisPromoter = myPromoter.getPromoterResult(itemID, dbConn);

	userName = myUser.getUser(thisPromoter.getUser_id(), dbConn).getUser_name();
	String timeCreated = thisPromoter.getCreate_date_as_string();
	String geneIDsAnalyzed = thisPromoter.getAnalyzed_ids();
	String geneIDsExcluded = thisPromoter.getExcluded_ids();
	GeneList promoterGeneList = thisPromoter.getPromoterGeneList();
	session.setAttribute("promoterGeneList", promoterGeneList);

	String geneListAnalysisDir = promoterGeneList.getGeneListAnalysisDir(userLoggedIn.getUserMainDir());
	String promoterDir = promoterGeneList.getOPOSSUMDir(geneListAnalysisDir);

	String filePrefix = promoterDir + timeCreated + "_"; 
	log.debug("filePrefix = " + filePrefix);
	session.setAttribute("filePrefix", filePrefix);

	String[] fisherResults = null;
	String[] zscoreResults = null;
	String[] outputResults = null;
	if ((new File(filePrefix + "fisher.txt")).exists()) {
		fisherResults = myFileHandler.getFileContents(new File(filePrefix + "fisher.txt"), "withSpaces");
		zscoreResults = myFileHandler.getFileContents(new File(filePrefix + "zscore.txt"), "withSpaces");
	} else if ((new File(filePrefix + "output.txt")).exists()) {
		outputResults= myFileHandler.getFileContents(new File(filePrefix + "output.txt"), "withSpaces");
	}

	String linkText = "<a href=\"" + geneListsDir + "targetGenes.jsp?tf=";
	String jasparLinkText = "<a href='' onClick=\"return popUpJaspar('http://asp.ii.uib.no:8090/cgi-bin/jaspar2005/jaspar_db.pl?ID=";
        mySessionHandler.createGeneListActivity(session.getId(), 
		promoterGeneList.getGene_list_id(),
                "Viewed Promoter Results",
		dbConn);

%>

<script language="JAVASCRIPT" type="text/javascript">
function popUpJaspar(url) {
        newWin=window.open(url, 'name', 
			'height=600,width=500,toolbar=0,location=50,directories=0,status=0,scrollbars=yes');
        if (window.focus) {
                newWin.focus()
        }
        return false;
}
</script>

<%@ include file="/web/common/header.jsp" %>
	<script type="text/javascript">
		crumbs = ["Home", "Research Genes", "Promoter"];
	</script>

	<%@ include file="/web/geneLists/include/viewingPane.jsp" %>

	<%@ include file="/web/geneLists/include/geneListToolsTabs.jsp" %>

	<div class="dataContainer" >
	<div id="related_links">
		<div class="action" title="Return to select a different promoter analysis">
			<a class="linkedImg return" href="promoter.jsp">
			<%=fiveSpaces%>
			Select Another Promoter Analysis
			</a>
		</div>
	</div>
	<div class="brClear"></div>

	<div class="title">Parameters Used</div> 
	<table class="list_base" cellpadding="0" cellspacing="3" width="70%">
		<tr class="col_title">
			<th class="noSort">Parameter Name</th>
			<th class="noSort">Value</th>
		</tr>
		<tr>
			<td width="30%"><b>Search Region Level:</b> </td>
			<td width="70%"><%=searchRegionLevelText%></td>
		</tr>
		<tr>
			<td width="30%"><b>Level of Conservation:</b> </td>
			<td width="70%"><%=conservationLevelText%></td>
		</tr>
		<tr>
			<td width="30%"><b>Matrix Match Threshold: </b></td>
			<td width="70%"><%=thresholdLevelText%></td>
		</tr>
<!-- 
		<tr>
			<td width="30%"><b>Genes Analyzed (Alternate RefSeq IDs in parentheses): </b></td>
			<td width="70%"><%=geneIDsAnalyzed%></td>
		</tr>
		<tr>
			<td width="30%"><b>Genes Excluded: </b></td>
			<td width="70%"><%=geneIDsExcluded%></td>
		</tr>
-->
	</table>
    <br>
    <a href="http://www.cisreg.ca/oPOSSUM/help.html#analysis_results" target="_blank">oPOSSUM Reference</a>
	<BR> <BR>
<% if ((new File(filePrefix + "fisher.txt")).exists()) { %>

	<div class="title"> One-Tailed Fisher Exact Probability Analysis</div>
	<table class="list_base tablesorter" cellpadding="0" cellspacing="3" width="98%">
		<thead>
		<tr class="col_title">
			<th> TF
			<th> Background Hits
			<th> Background Non-Hits
			<th> Target Gene Hits
			<th> Target Gene Non-Hits
			<th> P-value
		</tr>
		</thead>
		<tbody>
	<%

	//
	// The first line of this file is the column headers, so start reading from the second line
	//
	for (int i=1; i<fisherResults.length; i++) {
		%> <tr> <%
		String[] lineElements = fisherResults[i].split("\t");
                for (int j=0; j<lineElements.length; j++) {
			String[] columnSplit = lineElements[0].split(":::");
			// 
			// If this is the TF column, split it on ":::" and create a link to JASPAR
			//
			if (j == 0) {
				if (columnSplit.length == 1) {
					%> 
					<td><%=columnSplit[0]%></td> <%
				} else {
					%> 
					<td><%=jasparLinkText%><%=columnSplit[1]%>&amp;rm=present&amp;db=CORE')"><%=columnSplit[0]%></a></td> <%
				}
			// 
			// If this is the target gene hits column, build a link to another page
			//
			} else if (j == 3) {
				%> 
				<td><%=linkText%><%=columnSplit[0]%>"><%=lineElements[j]%></a></td> <%
			} else {
				%>
				<td> <%=lineElements[j]%> </td> <%
			}
                }
		%> </tr> <%
	}
	%>
	</tbody>
	</table>
	<BR>
	<BR>
	<div class="title"> Z-score Analysis</div>
	<table class="list_base tablesorter" cellpadding="0" cellspacing="3" width="98%">
		<thead>
		<tr class="col_title">
			<th> TF
			<th> Background TFBS Hits
			<th> Target TFBS Hits
			<th> Background TFBS rate
			<th> Target TFBS rate
			<th> Z-score
			<th> P-value
		</tr>
		</thead>
		<tbody>
	<% 	

	//
	// The first line of this file is the column headers, so start reading from the second line
	//
	for (int i=1; i<zscoreResults.length; i++) {
		%> <tr> <%
		String[] lineElements = zscoreResults[i].split("\t");
                for (int j=0; j<lineElements.length; j++) {
			String[] columnSplit = lineElements[0].split(":::");
			// 
			// If this is the TF column, split it on ":::" and create a link to JASPAR
			//
			if (j == 0) {
				if (columnSplit.length == 1) {
					%> 
					<td><%=columnSplit[0]%></td> <%
				} else {
					%> 
					<td><%=jasparLinkText%><%=columnSplit[1]%>&amp;rm=present')"><%=columnSplit[0]%></a></td> <%
				}
			// 
			// If this is the target tfbs hits column, build a link to another page
			//
			} else if (j == 2) {
				%> <td><%=linkText%><%=columnSplit[0]%>"><%=lineElements[j]%></a></td> <%
			// 
			// If this is the z-score column, calculate the p-value
			//
			} else if (j == 5) {
				double z = Math.abs(Double.parseDouble(lineElements[j]));  
				double pValue = 1 + z*(0.04986735+ z*(0.02114101+ z*(0.00327763+ z*(0.0000380036+ z*(0.0000488906+ z*0.000005383)))));
				String pValueFormatted = new DecimalFormat("#.#####").format(1/(Math.pow(pValue, 16))); 
				//log.debug("z-score = "+lineElements[j] + ", and p-Value = "+pValueFormatted);
				%> 
				<td><%=lineElements[j]%></td> <td><%=pValueFormatted%></td> <%
			} else {
				%> 
				<td> <%=lineElements[j]%> </td> <%
			}
                }
		%> </tr> <%
	}
	%>
	</tbody>
	</table>
<% } else { %>
	<BR>
	<div style="height:400px">
	<div class="title"> oPOSSUM Results</div>
	<table class="list_base tablesorter" cellpadding="0" cellspacing="3" width="98%">
		<thead>
		<tr class="col_title">
			<th> TF<BR>
                        	<span class="info" title="Transcription factor name">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			</th>
			<th> TF Class<BR>
                        	<span class="info" title="Transcription factor class (motif) name">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			</th>
			<th> TF SuperGroup<BR>
                        	<span class="info" title="The taxonomic supergroup to which this transcription factor belongs">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			</th>
			<th> IC<BR>
                        	<span class="info" title="The information content or specificity of this TFBS profile's position weight matrix">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			</th>
			<th> Background Gene Hits<BR>
                        	<span class="info" title="Number of genes in the background set with at least one TFBS predicted for this transciption factor">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			</th>
			<th> Background Gene Non-Hits<BR>
                        	<span class="info" title="Number of genes in the background set with NO TFBS predicted for this transciption factor">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			</th>
			<th> Target Gene Hits<BR>
                        	<span class="info" title="The number of (gene list) genes for which a transciption factor binding site (TFBS) is predicted">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> Target Gene Non-Hits<BR>
                        	<span class="info" title="The number of (gene list) genes for which no transciption factor binding site (TFBS) is predicted for this transcription factor">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> Background TFBS Hits<BR>
                        	<span class="info" title="The number of times this TFBS is predicted within the background set of genes">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> Background TFBS rate<BR>
                        	<span class="info" title="The rate of occurrence that this TFBS was detected within the conserved non-coding regions of the background set of genes">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> Target TFBS Hits<BR>
                        	<span class="info" title="The number of times this TFBS is predicted within the target genes (gene list)">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> Target TFBS rate<BR>
                        	<span class="info" title="The rate of occurrence that this TFBS was detected within the target genes (gene list)">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> Z-score<BR>
                        	<span class="info" title="A statistical measure that uses a simple binomial distribution model to compare the rate of occurrence of a TFBS in the target set of genes to the expected rate estimated from the pre-computed background set">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> Fisher score<BR>
                        	<span class="info" title="A one-tailed Fisher exact probability statistical measure to determine the over-representation of genes in the gene list with this TFBS compared to the background set of genes">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
			<th> P-value<BR>
                        	<span class="info" title="P-value associated with the z-score to test over-representation of TFBS within this set of genes">
                        	<img src="<%=imagesDir%>icons/info.gif" alt="Help">
                        	</span>
		</tr>
		</thead>
		<tbody>
	<% 	

	//
	// The first line of this file is the column headers, so start reading from the second line
	//
	for (int i=1; i<outputResults.length; i++) {
		%> <tr> <%
		String[] lineElements = outputResults[i].split("\t");
                for (int j=0; j<lineElements.length; j++) {
			// 
			// If this is the TF column, create a link to JASPAR using the second column
			//
			if (j == 0) {
				%> <td><%=jasparLinkText%><%=lineElements[1]%>&amp;rm=present&amp;db=CORE')"><%=lineElements[0]%></a></td> <%
			// 
			// If this is the second column, ignore it
			//
			} else if (j == 1) {
			// 
			// If this is the target tfbs hits column, build a link to another page
			//
			} else if (j == 7 || j == 11) {
				%>
				<td><%=linkText%><%=lineElements[0]%>"><%=lineElements[j]%></a></td> <%
			// 
			// If this is the last column, calculate the p-value based on the z-score
			//
			} else if (j == 14) {
				double z = Math.abs(Double.parseDouble(lineElements[j-1]));  
				double pValue = 1 + z*(0.04986735+ z*(0.02114101+ z*(0.00327763+ z*(0.0000380036+ z*(0.0000488906+ z*0.000005383)))));
				String pValueFormatted = new DecimalFormat("#.#####").format(1/(Math.pow(pValue, 16))); 
				pValueFormatted = (pValueFormatted.equals("0") ? "<0.00001" : pValueFormatted);
				//log.debug("z-score = "+lineElements[j] + ", and p-Value = "+pValueFormatted);
				%> 
				<td><%=lineElements[j]%></td> <td><%=pValueFormatted%></td> <%
			} else {
				%> 
				<td> <%=lineElements[j]%> </td> <%
			}
                }
		%> </tr> <%
	}
	%>
	</tbody>
	</table>
	</div>
<% } %>

<%@ include file="/web/common/footer.jsp" %>
